# Generated by Django 5.2.17 on 2026-09-29 07:04

import django.db.models.deletion
from django.db import migrations, models

import freeletter.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Issue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                ("slug", models.SlugField(max_length=255, unique=True, verbose_name="slug")),
                (
                    "subject",
                    models.CharField(
                        blank=True,
                        help_text="Defaults to the title if left blank.",
                        max_length=255,
                        verbose_name="email subject",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("queued", "Queued"), ("sent", "Sent")],
                        default="draft",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "queued_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="queued at"),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True, verbose_name="sent at")),
                (
                    "date_created",
                    models.DateTimeField(auto_now_add=True, verbose_name="date created"),
                ),
                ("date_updated", models.DateTimeField(auto_now=True, verbose_name="date updated")),
            ],
            options={
                "verbose_name": "issue",
                "verbose_name_plural": "issues",
                "ordering": ("-date_created",),
            },
        ),
        migrations.CreateModel(
            name="Subscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True, verbose_name="email")),
                ("name", models.CharField(blank=True, max_length=200, verbose_name="name")),
                ("is_confirmed", models.BooleanField(default=False, verbose_name="confirmed")),
                (
                    "confirmation_token",
                    models.CharField(
                        default=freeletter.models._token, editable=False, max_length=64, unique=True
                    ),
                ),
                (
                    "unsubscribe_token",
                    models.CharField(
                        default=freeletter.models._token, editable=False, max_length=64, unique=True
                    ),
                ),
                (
                    "subscribed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="subscribed at"),
                ),
                (
                    "confirmed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="confirmed at"),
                ),
                (
                    "unsubscribed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="unsubscribed at"),
                ),
            ],
            options={
                "verbose_name": "subscriber",
                "verbose_name_plural": "subscribers",
                "ordering": ("-subscribed_at",),
            },
        ),
        migrations.CreateModel(
            name="IssueBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("sortorder", models.PositiveIntegerField(default=0, verbose_name="sort order")),
                (
                    "block_type",
                    models.CharField(default="html", max_length=50, verbose_name="block type"),
                ),
                ("html", models.TextField(blank=True, verbose_name="content")),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="freeletter/blocks/%Y/%m/%d/", verbose_name="image"
                    ),
                ),
                (
                    "object_id",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="object id"),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                        verbose_name="content type",
                    ),
                ),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks",
                        to="freeletter.issue",
                        verbose_name="issue",
                    ),
                ),
            ],
            options={
                "verbose_name": "issue block",
                "verbose_name_plural": "issue blocks",
                "ordering": ("sortorder", "id"),
            },
        ),
    ]
